/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about2
     */
    public about() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        member1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        member2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        member3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        member4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        member5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        name2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        name3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        name4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        name9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 755));
        setPreferredSize(new java.awt.Dimension(1080, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        back.setFont(new java.awt.Font("Impact", 0, 56)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        back.setToolTipText("");
        back.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 620, 190, 80);

        jPanel2.setLayout(new java.awt.GridLayout(1, 5));

        member1.setBackground(new java.awt.Color(255, 255, 255));
        member1.setPreferredSize(new java.awt.Dimension(200, 300));
        member1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/golf.jpg"))); // NOI18N
        member1.add(jLabel3);

        jPanel2.add(member1);

        member2.setBackground(new java.awt.Color(255, 255, 255));
        member2.setPreferredSize(new java.awt.Dimension(200, 300));
        member2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pooh.jpg"))); // NOI18N
        member2.add(jLabel2);

        jPanel2.add(member2);

        member3.setBackground(new java.awt.Color(255, 255, 255));
        member3.setPreferredSize(new java.awt.Dimension(200, 300));
        member3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ramil.jpg"))); // NOI18N
        member3.add(jLabel4);

        jPanel2.add(member3);

        member4.setBackground(new java.awt.Color(255, 255, 255));
        member4.setPreferredSize(new java.awt.Dimension(200, 300));
        member4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/oil.jpg"))); // NOI18N
        member4.add(jLabel5);

        jPanel2.add(member4);

        member5.setBackground(new java.awt.Color(255, 255, 255));
        member5.setPreferredSize(new java.awt.Dimension(200, 300));
        member5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/peerakarn.jpg"))); // NOI18N
        member5.add(jLabel6);

        jPanel2.add(member5);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 150, 1080, 300);

        jPanel3.setLayout(new java.awt.GridLayout(1, 5));

        name1.setLayout(new java.awt.GridLayout(3, 0));

        jLabel23.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Passakorn  Nuchitkachornwut");
        name1.add(jLabel23);

        jLabel24.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("61070164");
        name1.add(jLabel24);

        jLabel25.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Dev");
        name1.add(jLabel25);

        jPanel3.add(name1);

        name2.setLayout(new java.awt.GridLayout(3, 0));

        jLabel22.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Poohcid  Rugravi");
        name2.add(jLabel22);

        jLabel26.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("61070166");
        name2.add(jLabel26);

        jLabel27.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Dev");
        name2.add(jLabel27);

        jPanel3.add(name2);

        name3.setLayout(new java.awt.GridLayout(3, 0));

        jLabel21.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Ramil  Arthan");
        name3.add(jLabel21);

        jLabel28.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("61070187");
        name3.add(jLabel28);

        jLabel29.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Dev");
        name3.add(jLabel29);

        jPanel3.add(name3);

        name4.setLayout(new java.awt.GridLayout(3, 0));

        jLabel15.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Littikrai  Sakunpaisawari");
        name4.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("61070191");
        jLabel16.setToolTipText("");
        name4.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Dev");
        name4.add(jLabel17);

        jPanel3.add(name4);

        name9.setLayout(new java.awt.GridLayout(3, 0));

        jLabel18.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Peerakarn  Dechvilairueng ");
        name9.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("61070147");
        jLabel19.setToolTipText("");
        name9.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Dev");
        name9.add(jLabel20);

        jPanel3.add(name9);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 450, 1080, 120);

        title1.setFont(new java.awt.Font("Impact", 0, 56)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Provider");
        title1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(title1);
        title1.setBounds(0, 30, 1080, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        background.setMinimumSize(new java.awt.Dimension(1080, 720));
        background.setPreferredSize(new java.awt.Dimension(1899, 1416));
        jPanel1.add(background);
        background.setBounds(0, -70, 1940, 1416);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        Home f = new Home();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.setVisible(false);
         f.setTitle("Big Gun");
    }//GEN-LAST:event_backMousePressed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back2.png")));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
           back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png")));
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new about().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel member1;
    private javax.swing.JPanel member2;
    private javax.swing.JPanel member3;
    private javax.swing.JPanel member4;
    private javax.swing.JPanel member5;
    private javax.swing.JPanel name1;
    private javax.swing.JPanel name2;
    private javax.swing.JPanel name3;
    private javax.swing.JPanel name4;
    private javax.swing.JPanel name9;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
