/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        htplay = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2080, 1500));
        setMinimumSize(new java.awt.Dimension(1080, 755));
        setPreferredSize(new java.awt.Dimension(1080, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(2500, 2500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 160, 510, 400);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/start.png"))); // NOI18N
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startMousePressed(evt);
            }
        });
        jPanel1.add(start);
        start.setBounds(620, 190, 352, 95);

        htplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/htp.png"))); // NOI18N
        htplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                htplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                htplayMouseExited(evt);
            }
        });
        jPanel1.add(htplay);
        htplay.setBounds(620, 320, 352, 95);

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/about.png"))); // NOI18N
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutMousePressed(evt);
            }
        });
        jPanel1.add(about);
        about.setBounds(620, 440, 352, 95);

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        backgound.setMinimumSize(new java.awt.Dimension(1080, 720));
        backgound.setPreferredSize(new java.awt.Dimension(1899, 1416));
        jPanel1.add(backgound);
        backgound.setBounds(0, -70, 1940, 1416);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMousePressed
        // TODO add your handling code here:
        setting f = new setting();
        f.setTitle("Big Gun");
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_startMousePressed

    private void htplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_htplayMouseEntered
        // TODO add your handling code here:
        htplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/htp_2.png")));
    }//GEN-LAST:event_htplayMouseEntered

    private void htplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_htplayMouseExited
        // TODO add your handling code here:
          htplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/htp.png")));
    }//GEN-LAST:event_htplayMouseExited

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        // TODO add your handling code here:
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/about_2.png")));
    }//GEN-LAST:event_aboutMouseEntered

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        // TODO add your handling code here:
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/about.png")));
    }//GEN-LAST:event_aboutMouseExited

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
        // TODO add your handling code here:
        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/start.png")));
    }//GEN-LAST:event_startMouseExited

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        // TODO add your handling code here:
           start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button_home/start_2.png")));
    }//GEN-LAST:event_startMouseEntered

    private void aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMousePressed
        // TODO add your handling code here:
        about f = new about();
        f.setTitle("Big Gun");
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_aboutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home h = new Home();
                h.setTitle("Big Gun");
                h.setVisible(true);
                h.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel backgound;
    private javax.swing.JLabel htplay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
