/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class setting extends javax.swing.JFrame {

    /**
     * Creates new form setting
     */
    public setting() {
        initComponents();
    }

    public void setResolution(String size){
        if(size.equals("800 x 600")){
            width = 800;
            height = 600;
        }
        if(size.equals("1024 x 768")){
            width = 1024;
            height = 768; 
        }
        if(size.equals("1280 x 720")){
            width = 1280;
            height = 720; 
        }
        if(size.equals("1360 x 768")){
            width = 1360;
            height = 768; 
        }
        if(size.equals("1440 x 1050")){
            width = 1440;
            height = 1050; 
        }
        if(size.equals("1680 x 900")){
            width = 1680;
            height = 900; 
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        enemy = new javax.swing.JComboBox<>();
        resolution = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        bnConfirm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 755));
        setMinimumSize(new java.awt.Dimension(1080, 755));
        setPreferredSize(new java.awt.Dimension(1080, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amount of Enemies");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(385, 300, 280, 50);

        enemy.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        enemy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel2.add(enemy);
        enemy.setBounds(400, 380, 250, 40);

        resolution.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resolution.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "800 x 600", "1024 x 768", "1280 x 720", "1360 x 768", "1440 x 1050", "1680 x 900" }));
        jPanel2.add(resolution);
        resolution.setBounds(400, 230, 250, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Game Resolution");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(400, 150, 250, 50);

        bnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c2.png"))); // NOI18N
        bnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnConfirmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bnConfirmMousePressed(evt);
            }
        });
        jPanel2.add(bnConfirm);
        bnConfirm.setBounds(400, 460, 254, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -70, 1899, 1416);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConfirmMouseEntered
        // TODO add your handling code here:
        bnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c.png")));
    }//GEN-LAST:event_bnConfirmMouseEntered

    private void bnConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConfirmMouseExited
        // TODO add your handling code here:
        bnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c2.png")));        
    }//GEN-LAST:event_bnConfirmMouseExited

    private void bnConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConfirmMousePressed
        // TODO add your handling code here:
        setResolution(resolution.getSelectedItem().toString());
        enemys = Integer.parseInt(enemy.getSelectedItem().toString());
        prePlay f = new prePlay(width, height, enemys);
        f.setTitle("Big Gun");
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_bnConfirmMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new setting().setVisible(true);
        });
    }
    private int width, height, enemys;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bnConfirm;
    private javax.swing.JComboBox<String> enemy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> resolution;
    // End of variables declaration//GEN-END:variables
}
