/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class setting extends javax.swing.JFrame {

    /**
     * Creates new form setting
     */
    public setting() {
        initComponents();
        setLevel(1); 
    }
   
    public void setResolution(String size){
        if(size.equals("800 x 600")){
            width = 800;
            height = 600;
        }
        if(size.equals("1024 x 768")){
            width = 1024;
            height = 768; 
        }
        if(size.equals("1280 x 720")){
            width = 1280;
            height = 720; 
        }
        if(size.equals("1360 x 768")){
            width = 1360;
            height = 768; 
        }
        if(size.equals("1440 x 1050")){
            width = 1440;
            height = 1050; 
        }
        if(size.equals("1680 x 900")){
            width = 1680;
            height = 900; 
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resolution = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        bnConfirm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enemy = new javax.swing.JComboBox<>();
        normaly = new javax.swing.JLabel();
        hard = new javax.swing.JLabel();
        easy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 755));
        setMinimumSize(new java.awt.Dimension(1080, 755));
        setPreferredSize(new java.awt.Dimension(1080, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Difficulty Level");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(410, 350, 220, 50);

        resolution.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resolution.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "800 x 600", "1024 x 768", "1280 x 720", "1360 x 768", "1440 x 1050", "1680 x 900" }));
        jPanel2.add(resolution);
        resolution.setBounds(400, 170, 250, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Game Resolution");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(400, 100, 250, 50);

        bnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c2.png"))); // NOI18N
        bnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnConfirmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bnConfirmMousePressed(evt);
            }
        });
        jPanel2.add(bnConfirm);
        bnConfirm.setBounds(400, 490, 254, 70);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount of Enemies");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(385, 230, 280, 50);

        enemy.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        enemy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "5", "8", "10" }));
        jPanel2.add(enemy);
        enemy.setBounds(400, 300, 250, 40);

        normaly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        normaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/normaly.png"))); // NOI18N
        normaly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                normalyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                normalyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                normalyMousePressed(evt);
            }
        });
        jPanel2.add(normaly);
        normaly.setBounds(440, 410, 140, 70);

        hard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/h1.png"))); // NOI18N
        hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hardMousePressed(evt);
            }
        });
        jPanel2.add(hard);
        hard.setBounds(590, 410, 140, 70);

        easy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/easy.png"))); // NOI18N
        easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                easyMousePressed(evt);
            }
        });
        jPanel2.add(easy);
        easy.setBounds(290, 410, 140, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -70, 1899, 1416);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void setLevel(int l){
        switch(l){
            case 1:
                this.level = "easy";
                easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/easyhold.png")));  
                normaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/normaly.png")));
                hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/h1.png")));
                break;
            case 2:
                this.level = "normal";
                normaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/normalyhold.png")));
                easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/easy.png")));
                hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/h1.png")));
                break;
            case 3:
                this.level = "hard";
                hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/h1hold.png")));
                normaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/normaly.png")));
                easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/easy.png")));
                break;
        }
    }
    private void bnConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConfirmMouseEntered
        // TODO add your handling code here:
        bnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c.png")));
    }//GEN-LAST:event_bnConfirmMouseEntered

    private void bnConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConfirmMouseExited
        // TODO add your handling code here:
        bnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c2.png")));        
    }//GEN-LAST:event_bnConfirmMouseExited

    private void bnConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConfirmMousePressed
        // TODO add your handling code here:
        setResolution(resolution.getSelectedItem().toString());
        enemys = Integer.parseInt(enemy.getSelectedItem().toString());
        prePlay f = new prePlay(width, height, enemys, level);
        f.setTitle("Big Gun");
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_bnConfirmMousePressed

    private void easyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMousePressed
        // TODO add your handling code here: 
        setLevel(1);        
    }//GEN-LAST:event_easyMousePressed

    private void easyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseEntered
        // TODO add your handling code here:
          if(!level.equals("easy"))easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/easyen.png")));
          
    }//GEN-LAST:event_easyMouseEntered

    private void easyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseExited
        // TODO add your handling code here:
        if(!level.equals("easy"))easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/easy.png")));  
    }//GEN-LAST:event_easyMouseExited

    private void normalyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalyMouseEntered
        // TODO add your handling code here:
        if(!level.equals("normal"))normaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/normalyen.png")));  
    }//GEN-LAST:event_normalyMouseEntered

    private void normalyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalyMouseExited
        // TODO add your handling code here:
       if(!level.equals("normal"))normaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/normaly.png")));  
    }//GEN-LAST:event_normalyMouseExited

    private void normalyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalyMousePressed
        // TODO add your handling code here:
        setLevel(2);
    }//GEN-LAST:event_normalyMousePressed

    private void hardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseEntered
        // TODO add your handling code here:
        if(!level.equals("hard"))hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/h1en.png")));  
    }//GEN-LAST:event_hardMouseEntered

    private void hardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseExited
        // TODO add your handling code here:
        if(!level.equals("hard"))hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/h1.png")));  
    }//GEN-LAST:event_hardMouseExited

    private void hardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMousePressed
        // TODO add your handling code here:
        setLevel(3);
    }//GEN-LAST:event_hardMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new setting().setVisible(true);
//        });
//    }
    private String level="easy";
    private int width, height, enemys;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bnConfirm;
    private javax.swing.JLabel easy;
    private javax.swing.JComboBox<String> enemy;
    private javax.swing.JLabel hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel normaly;
    private javax.swing.JComboBox<String> resolution;
    // End of variables declaration//GEN-END:variables
}
