/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        howToPlay = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        backgound = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(80, 160, 510, 400);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/start.png"))); // NOI18N
        add(start);
        start.setBounds(630, 150, 352, 95);

        howToPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/setting.png"))); // NOI18N
        add(howToPlay);
        howToPlay.setBounds(630, 390, 352, 95);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/htp.png"))); // NOI18N
        add(setting);
        setting.setBounds(630, 270, 352, 95);

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/about.png"))); // NOI18N
        add(about);
        about.setBounds(630, 510, 352, 95);

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        backgound.setMinimumSize(new java.awt.Dimension(1080, 720));
        backgound.setPreferredSize(new java.awt.Dimension(1899, 1416));
        add(backgound);
        backgound.setBounds(0, -70, 1940, 1416);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel backgound;
    private javax.swing.JLabel howToPlay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
