/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class prePlay extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public prePlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JLabel();
        moneyPanel = new javax.swing.JPanel();
        labelMoney = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        backgound = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/button (5).png"))); // NOI18N
        add(start);
        start.setBounds(900, 20, 160, 70);

        moneyPanel.setBackground(new java.awt.Color(102, 102, 102));
        moneyPanel.setLayout(new java.awt.GridLayout(2, 0));

        labelMoney.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelMoney.setForeground(new java.awt.Color(255, 255, 255));
        labelMoney.setText(" Money");
        moneyPanel.add(labelMoney);

        money.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        money.setForeground(new java.awt.Color(255, 255, 255));
        money.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        money.setText("200 $ ");
        money.setToolTipText("");
        moneyPanel.add(money);

        add(moneyPanel);
        moneyPanel.setBounds(20, 20, 170, 70);

        title.setFont(new java.awt.Font("Impact", 1, 56)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CHOSE YOUR THNK");
        add(title);
        title.setBounds(320, 20, 460, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(102, 255, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(102, 255, 102));
        jPanel4.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel4);
        jPanel4.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setForeground(new java.awt.Color(102, 255, 102));
        jPanel5.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel5);
        jPanel5.getAccessibleContext().setAccessibleName("");

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setForeground(new java.awt.Color(102, 255, 102));
        jPanel6.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel6);
        jPanel6.getAccessibleContext().setAccessibleName("");

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setForeground(new java.awt.Color(102, 255, 102));
        jPanel7.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel7);
        jPanel7.getAccessibleContext().setAccessibleName("");

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setForeground(new java.awt.Color(102, 255, 102));
        jPanel8.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel8);
        jPanel8.getAccessibleContext().setAccessibleName("");

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setForeground(new java.awt.Color(102, 255, 102));
        jPanel9.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel9.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel9);
        jPanel9.getAccessibleContext().setAccessibleName("");

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(102, 255, 102));
        jPanel10.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel10.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel10);
        jPanel10.getAccessibleContext().setAccessibleName("");

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setForeground(new java.awt.Color(102, 255, 102));
        jPanel11.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel11.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel11);
        jPanel11.getAccessibleContext().setAccessibleName("");

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setForeground(new java.awt.Color(102, 255, 102));
        jPanel12.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel12);
        jPanel12.getAccessibleContext().setAccessibleName("");

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setForeground(new java.awt.Color(102, 255, 102));
        jPanel13.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel13);
        jPanel13.getAccessibleContext().setAccessibleName("");

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setForeground(new java.awt.Color(102, 255, 102));
        jPanel14.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel14.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel14);
        jPanel14.getAccessibleContext().setAccessibleName("");

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setForeground(new java.awt.Color(102, 255, 102));
        jPanel15.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel15.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel15);
        jPanel15.getAccessibleContext().setAccessibleName("");

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setForeground(new java.awt.Color(102, 255, 102));
        jPanel16.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel16.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel16);
        jPanel16.getAccessibleContext().setAccessibleName("");

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel17.setForeground(new java.awt.Color(102, 255, 102));
        jPanel17.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel17.setPreferredSize(new java.awt.Dimension(250, 140));
        jPanel2.add(jPanel17);
        jPanel17.getAccessibleContext().setAccessibleName("");

        add(jPanel2);
        jPanel2.setBounds(20, 110, 1040, 600);

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        backgound.setMinimumSize(new java.awt.Dimension(1080, 720));
        backgound.setPreferredSize(new java.awt.Dimension(1899, 1416));
        add(backgound);
        backgound.setBounds(0, -70, 1940, 1416);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgound;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelMoney;
    private javax.swing.JLabel money;
    private javax.swing.JPanel moneyPanel;
    private javax.swing.JLabel start;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
