/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author PCoil
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        howToPlay = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2080, 1500));
        setMinimumSize(new java.awt.Dimension(1080, 755));
        setPreferredSize(new java.awt.Dimension(1080, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(2500, 2500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 160, 510, 400);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/start.png"))); // NOI18N
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        jPanel1.add(start);
        start.setBounds(630, 150, 352, 95);

        howToPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/setting.png"))); // NOI18N
        jPanel1.add(howToPlay);
        howToPlay.setBounds(630, 390, 352, 95);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/htp.png"))); // NOI18N
        jPanel1.add(setting);
        setting.setBounds(630, 270, 352, 95);

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/about.png"))); // NOI18N
        jPanel1.add(about);
        about.setBounds(630, 510, 352, 95);

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/opl.jpg"))); // NOI18N
        backgound.setMinimumSize(new java.awt.Dimension(1080, 720));
        backgound.setPreferredSize(new java.awt.Dimension(1899, 1416));
        jPanel1.add(backgound);
        backgound.setBounds(0, -70, 1940, 1416);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
        setting f = new setting();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_startMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home h = new Home();
                h.setVisible(true);
                h.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel backgound;
    private javax.swing.JLabel howToPlay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
